# Generated by Django 4.0.4 on 2022-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
